"""Service layer for Invite management operations.

All database interactions for the Invite resource live here.  Route
handlers call these functions and handle HTTP-level concerns (status codes,
response shaping) separately.

Functions are stateless — each accepts a SQLAlchemy ``Session`` as its
first argument.

Business rules enforced here:
- Invites are created with a ULID as the primary key (the id IS the code).
- Only unconsumed invites may be deleted (hard delete).
- Consumed invites cannot be deleted — this is enforced at the service layer.
"""

from __future__ import annotations

from sqlalchemy import select
from sqlalchemy.orm import Session

from wizards_engine.models.user import Invite
from wizards_engine.roles import Role

__all__ = [
    "create_invite",
    "get_invite",
    "list_invites_query",
    "delete_invite",
]


def create_invite(db: Session, *, role: str = Role.PLAYER) -> Invite:
    """Create a new invite and persist it.

    The invite ID (ULID) is auto-generated by the model default and serves
    as the shareable code.  No character is pre-linked — the invite is bare.

    Args:
        db: Active SQLAlchemy session.
        role: The role to assign when this invite is redeemed.  Must be
            ``"player"`` or ``"viewer"``; defaults to ``"player"``.

    Returns:
        The newly created and flushed :class:`~wizards_engine.models.user.Invite`
        instance with its auto-generated ``id`` populated.
    """
    invite = Invite(role=role)
    db.add(invite)
    db.flush()
    db.refresh(invite)
    return invite


def get_invite(db: Session, invite_id: str) -> Invite | None:
    """Retrieve a single Invite by its ULID.

    Args:
        db: Active SQLAlchemy session.
        invite_id: ULID primary key (also the shareable code).

    Returns:
        The :class:`~wizards_engine.models.user.Invite` if found,
        or ``None`` if no row exists with that ID.
    """
    return db.get(Invite, invite_id)


def list_invites_query(db: Session):
    """Build a SQLAlchemy select statement for the Invites list.

    Returns all invites (consumed and unconsumed).  The caller
    (``api.pagination.paginate``) adds ordering and LIMIT.

    Args:
        db: Active SQLAlchemy session.

    Returns:
        A SQLAlchemy ``Select`` statement targeting :class:`~wizards_engine.models.user.Invite`.
    """
    return select(Invite)


def delete_invite(db: Session, invite: Invite) -> None:
    """Hard-delete *invite* from the database.

    Only unconsumed invites should be deleted — the caller must enforce this
    by checking ``invite.is_consumed`` before calling.

    Args:
        db: Active SQLAlchemy session.
        invite: The ORM instance to hard-delete.
    """
    db.delete(invite)
    db.flush()
