"""initial_schema

Revision ID: b34ed29cf3a3
Revises: 
Create Date: 2026-03-16 09:13:02.660915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b34ed29cf3a3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('detail_level', sa.String(length=20), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('stress', sa.Integer(), nullable=True),
    sa.Column('free_time', sa.Integer(), nullable=True),
    sa.Column('plot', sa.Integer(), nullable=True),
    sa.Column('gnosis', sa.Integer(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('magic_stats', sa.JSON(), nullable=True),
    sa.Column('last_session_time_now', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clocks',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('segments', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('associated_type', sa.String(length=20), nullable=True),
    sa.Column('associated_id', sa.String(length=26), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('groups',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invites',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('is_consumed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.String(length=26), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['locations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('time_now', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stories',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('parent_id', sa.String(length=26), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('visibility_level', sa.String(length=20), nullable=True),
    sa.Column('visibility_overrides', sa.JSON(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['stories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trait_templates',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('magic_effects',
    sa.Column('character_id', sa.String(length=26), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('effect_type', sa.String(length=20), nullable=False),
    sa.Column('power_level', sa.Integer(), nullable=False),
    sa.Column('charges_current', sa.Integer(), nullable=True),
    sa.Column('charges_max', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_magic_effects_character_id'), 'magic_effects', ['character_id'], unique=False)
    op.create_table('session_participants',
    sa.Column('session_id', sa.String(length=26), nullable=False),
    sa.Column('character_id', sa.String(length=26), nullable=False),
    sa.Column('additional_contribution', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', 'character_id')
    )
    op.create_table('slots',
    sa.Column('slot_type', sa.String(length=30), nullable=False),
    sa.Column('owner_type', sa.String(length=20), nullable=False),
    sa.Column('owner_id', sa.String(length=26), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=True),
    sa.Column('target_id', sa.String(length=26), nullable=True),
    sa.Column('source_label', sa.String(length=200), nullable=True),
    sa.Column('target_label', sa.String(length=200), nullable=True),
    sa.Column('bidirectional', sa.Boolean(), nullable=True),
    sa.Column('template_id', sa.String(length=26), nullable=True),
    sa.Column('charge', sa.Integer(), nullable=True),
    sa.Column('stress', sa.Integer(), nullable=True),
    sa.Column('stress_degradations', sa.Integer(), nullable=True),
    sa.Column('is_trauma', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['trait_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_slots_owner', 'slots', ['owner_type', 'owner_id', 'slot_type'], unique=False)
    op.create_index('ix_slots_target', 'slots', ['target_type', 'target_id'], unique=False)
    op.create_table('story_owners',
    sa.Column('story_id', sa.String(length=26), nullable=False),
    sa.Column('owner_type', sa.String(length=20), nullable=False),
    sa.Column('owner_id', sa.String(length=26), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('story_id', 'owner_type', 'owner_id')
    )
    op.create_table('users',
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('login_code', sa.String(), nullable=False),
    sa.Column('character_id', sa.String(length=26), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id')
    )
    op.create_index(op.f('ix_users_login_code'), 'users', ['login_code'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('actor_type', sa.String(length=10), nullable=False),
    sa.Column('actor_id', sa.String(length=26), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.Column('created_objects', sa.JSON(), nullable=True),
    sa.Column('deleted_objects', sa.JSON(), nullable=True),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('proposal_id', sa.String(length=26), nullable=True),
    sa.Column('parent_event_id', sa.String(length=26), nullable=True),
    sa.Column('session_id', sa.String(length=26), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_event_id'], ['events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], name='fk_events_proposal_id', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_actor_id'), 'events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_events_proposal_id'), 'events', ['proposal_id'], unique=False)
    op.create_index(op.f('ix_events_session_id'), 'events', ['session_id'], unique=False)
    op.create_table('starred_objects',
    sa.Column('user_id', sa.String(length=26), nullable=False),
    sa.Column('object_type', sa.String(length=20), nullable=False),
    sa.Column('object_id', sa.String(length=26), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'object_type', 'object_id')
    )
    op.create_table('event_targets',
    sa.Column('event_id', sa.String(length=26), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.String(length=26), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'target_type', 'target_id')
    )
    op.create_table('proposals',
    sa.Column('character_id', sa.String(length=26), nullable=True),
    sa.Column('action_type', sa.String(length=30), nullable=False),
    sa.Column('origin', sa.String(length=10), nullable=False),
    sa.Column('narrative', sa.Text(), nullable=False),
    sa.Column('selections', sa.JSON(), nullable=False),
    sa.Column('calculated_effect', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('gm_notes', sa.Text(), nullable=True),
    sa.Column('gm_overrides', sa.JSON(), nullable=True),
    sa.Column('event_id', sa.String(length=26), nullable=True),
    sa.Column('clock_id', sa.String(length=26), nullable=True),
    sa.Column('rider_event_id', sa.String(length=26), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['clock_id'], ['clocks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rider_event_id'], ['events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposals_character_id'), 'proposals', ['character_id'], unique=False)
    op.create_index(op.f('ix_proposals_event_id'), 'proposals', ['event_id'], unique=False)
    op.create_table('story_entries',
    sa.Column('story_id', sa.String(length=26), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('author_id', sa.String(length=26), nullable=False),
    sa.Column('character_id', sa.String(length=26), nullable=True),
    sa.Column('session_id', sa.String(length=26), nullable=True),
    sa.Column('event_id', sa.String(length=26), nullable=True),
    sa.Column('game_object_refs', sa.JSON(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_by', sa.String(length=26), nullable=True),
    sa.Column('updated_by', sa.String(length=26), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_entries_author_id'), 'story_entries', ['author_id'], unique=False)
    op.create_index(op.f('ix_story_entries_story_id'), 'story_entries', ['story_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_story_entries_story_id'), table_name='story_entries')
    op.drop_index(op.f('ix_story_entries_author_id'), table_name='story_entries')
    op.drop_table('story_entries')
    op.drop_index(op.f('ix_proposals_event_id'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_character_id'), table_name='proposals')
    op.drop_table('proposals')
    op.drop_table('event_targets')
    op.drop_table('starred_objects')
    op.drop_index(op.f('ix_events_session_id'), table_name='events')
    op.drop_index(op.f('ix_events_proposal_id'), table_name='events')
    op.drop_index(op.f('ix_events_actor_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_users_login_code'), table_name='users')
    op.drop_table('users')
    op.drop_table('story_owners')
    op.drop_index('ix_slots_target', table_name='slots')
    op.drop_index('ix_slots_owner', table_name='slots')
    op.drop_table('slots')
    op.drop_table('session_participants')
    op.drop_index(op.f('ix_magic_effects_character_id'), table_name='magic_effects')
    op.drop_table('magic_effects')
    op.drop_table('trait_templates')
    op.drop_table('stories')
    op.drop_table('sessions')
    op.drop_table('locations')
    op.drop_table('invites')
    op.drop_table('groups')
    op.drop_table('clocks')
    op.drop_table('characters')
    # ### end Alembic commands ###
